### PR TITLE
Add Python script to scan for wifi networks.

### LINKED ISSUE #55: Standardize the iwlist scan regardless of driver/adapter
The result of `iwlist scan` can vary if one is using an external usb wifi adapter instead the internal wifi module from the rpi for example, and that can break the way the list is shown. 

For example, when using a TP/Link wifi adapter, `iwlist scan` driver can return:  
`Quality=70/70  Signal level=-40/100` while the internal RPi Realtek driver returns `Quality=70/70  Signal level=-40 dBm`.

This difference affects the mechanism to order the list by the network which has the best signal, consequently breaking it.

### PR DESCRIPTION
**Pull request by mrstegeman**
This should give us a much more consistent output.

Also, fix a couple things:
* Ellipsize long network names to prevent overflowing.
* Escape SSIDs with quotes in them.

Fixes #55

### CODE REVIEW

**Comment by mrstegeman** [comment]
@andrenatal This has all been tested and is working, though I don't have a USB wifi dongle to test with.

**Comment by andrenatal** [comment]
@mrstegeman Cool, I have a wifi dongle and a rpi without an internal module here to test. Let me do it.

**Comment by andrenatal** [comment]
Tested and worked with both external and internal wifi adapters. Thanks!

**Review by andrenatal — COMMENTED** [review]
Working fine!

**Pull request merged**
