### PR TITLE
Submit when Enter is hit and the password textbox is focused

### LINKED ISSUE #27: Captive portal doesn't respond to 'Go' key on keyboard
When connecting to a wireless network and I'm entering the password (on my iOS device), there is a button at the bottom right corner of the keyboard, I think it was called 'Go'. If I press that button, then it just dumps me back to the SSID list and doesn't connect. I have to press the 'Connect' button otherwise it doesn't connect.

Pressing 'Go' (or whatever it was called) should behave the same as pressing 'Connect'

### PR DESCRIPTION
**Pull request by andrenatal**
fixes #27

### CODE REVIEW

**Comment by dhylands** [comment]
I'm going to suggest that ben (or somebody else more familiar with UI stuff) review this. I haven't got a clue whether this is a good change or not.

**Comment by andrenatal** [comment]
I'll add James too just in case Ben is gone for the day already.

**Comment by benfrancis** [comment]
Fine from a UI point of view, but detecting keycodes is a bit brittle, you'd be better off listening for a submit event on a form. See https://github.com/mozilla-iot/gateway/blob/master/static/js/login.js#L17

**Comment by andrenatal** [comment]
Turns out the solution was actually way simpler. Changing the back button to an `input` instead a `button` made Safari starting to properly submit the form.  @benfrancis r?

**Comment by andrenatal** [comment]
@hobinjk r?

**Review by hobinjk — APPROVED** [review]
Looks reasonable to me

**Pull request merged**
