### PR TITLE
Make gateway.local message a link.

### LINKED ISSUE #50: Make "gateway.local" message a link
During first time setup there's a message which tells you to type gateway.local into your browser. It would be nice if this was a link so I don't have to type it in!

Would need testing in the captive portal UI to check it opens in a separate browser window (target=blank?).

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #50

### CODE REVIEW

**Comment by andrenatal** [comment]
The code LGTM.  Did you test it?

**Review by andrenatal — APPROVED** [review]

**Comment by andrenatal** [comment]
I think we should also display this message in the password page, because after inputting the password, the hotspot is shutdown and user's wifi get disconnected, making the captive portal be closed too fast by the OS, thus not giving enough time to let the user even see this confirmation page. 

Or we can add a delay of some seconds to let the user see this message before shutdown hostapd.

**Comment by mrstegeman** [comment]
Yep, works fine.

**Comment by benfrancis** [comment]
@mrstegeman Sorry for the late review, but can you make the link white please (including :hover and :active states)? It's barely readable with the default color.

**Comment by mrstegeman** [comment]
@benfrancis https://github.com/mozilla-iot/gateway-wifi-setup/pull/59

**Pull request merged**
