### PR TITLE
Broadcast an Eddystone beacon after wifi setup.

### LINKED ISSUE #60: Broadcast a Eddystone Beacon message in the First-time setup with the gateway's local IP address
Re: https://github.com/mozilla-iot/gateway/issues/714

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #60

### CODE REVIEW

**Review by andrenatal — APPROVED** [review]
didn't test but code looks good. thanks!

**Comment by benfrancis** [comment]
Thanks for working on this, I have some questions.

What does this actually broadcast and when? I can't quite tell from the code.

My understanding was that the intended use case was to provide a Bluetooth broadcast as an alternative to an mDNS broadcast for Android, which doesn't support mDNS at the OS level. The main purpose of the mDNS broadcast is to make the gateway accessible over gateway.local for first time setup, either when using Ethernet or after connecting WiFi and before a subdomain is defined.

So is this broadcasting a local IP address to help with first time setup, either over Ethernet or after WiFi setup? What metadata is included and how does it appear in the system UI on Android?

Allowing mDNS to continue to broadcast after first time setup is relatively harmless because it's only on the users' own local network, and is useful if local access is needed (albeit with an unfriendly UI where you have to add a security exception) or if the user opts out of a public sub-domain.

But do we want Bluetooth to continue to broadcast after first time setup given anyone nearby can see this broadcast? Is that not a privacy risk? If it does broadcast after first time setup then maybe we want it to broadcast the public domain rather than the private IP, so that additional users or Android devices can discover and log into the gateway.

To be on the safe side I'd suggest just broadcasting a local IP for first time setup and then disabling the broadcast after that. Unless you think there's a compelling use case for continuing to broadcast? And if so, should it broadcast the local IP/domain or public domain?

**Comment by mrstegeman** [comment]
@benfrancis This will just broadcast the local IP address (and nothing else) after either setting up a wifi network or clicking Skip. It will look for an IP address on wlan0 first, then go to eth0 if wifi wasn't set up. The beacon just pops up as a notification in and Android UI, and when you click on it, it will browse to the included URL (the IP address).

This does not conflict at all with mDNS, it's just another broadcast. mDNS will continue to function as usual.

As for the rest of your comment, the broadcast will only occur once, after initial wifi setup, and will only continue until the RPi is rebooted. Given that this broadcast is done by the wifi-setup code, it no longer has the control to disable the broadcast. That would have to be done by the gateway. While that's entirely possible, we're then starting to put board-specific code into the gateway, because the Bluetooth beacon only applies to our specific RPi image.

That said, I'm happy to put some code to disable the beacon in the gateway itself, if that's what we want.

**Comment by benfrancis** [comment]
OK, I see. Maybe we should just land this and file a follow-up to figure out how to more cleanly turn the broadcast off after setup, and/or discuss potential use cases for it after setup (e.g. for a Things Browser to discover a Things Gateway).

I'd still be interested to see how this broadcast appears in the Android system UI and whether there's a way of serving additional metadata from the URL which a client (e.g. a Things Browser) could use to provide more useful information, but that's possibly a separate topic. Note that [Project Magnet](https://wiki.mozilla.org/Connected_Devices/Projects/Project_Magnet) previously did a lot of work in this area, but with a different set of use cases around content discovery rather than device discovery.

**Review by benfrancis — APPROVED** [review]

**Pull request merged**
